### ISSUE TITLE
Test connections is ok, but there is error in the 'Schemes list'

### ISSUE THREAD

**Issue by garm-su** [tarantool/tarantool-idea-plugin#15]
[Screen](https://cloud.garm.work/s/wTbENmitc5ayRjA/preview)
[ide.log.txt](https://github.com/tarantool/tarantool-idea-plugin/files/7176743/ide.log.txt)

**Comment by Periecle** [comment]
The team determined that the used Tarantool version does not support SQL interaction, and therefore can not be used with this plugin. We will update the documentation with the supported Tarantool versions.
