### ISSUE TITLE
Use extension to provide DBMS

### ISSUE THREAD

**Issue by kassak** [tarantool/tarantool-idea-plugin#6]
https://github.com/tarantool/tarantool-idea-plugin/blob/4558c5df9d71a5505562eecb0e9342d22064aa1f/src/main/scala/io/tarantool/idea/plugin/sql/DbmsHolder.java#L10

There is an extension for that, see
com.intellij.database.Dbms.DbmsBean

**Comment by Teinnsei** [comment]
@kassak thanks for this help
